POST http://localhost:8091/error-tag
Content-Type: application/json

{
  "tags": [
    {
      "name": "tag1"
    },
    {
      "name": "tag2"
    },
    {
      "name": "tag3"
    }
  ],
  "description": "first error"
}

###
POST http://localhost:8091/error-tag
Content-Type: application/json

{
  "tags": [
    {
      "id": 3,
      "name": "tag3"
    }
  ],
  "description": "second error"
}

###
GET http://localhost:8091/error-tag

###
GET http://localhost:8091/error-description/3
