server:
  port: 8091

spring:
  datasource:
    url: jdbc:h2:mem:review

  sql:
    init:
      mode: always


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true
