DROP TABLE IF EXISTS TYPICAL_ERROR_COMMENT;

CREATE TABLE TYPICAL_ERROR_COMMENT
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE       TEXT,
    DESCRIPTION TEXT
);

CREATE TABLE ERROR_COMMENT
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION TEXT
);

CREATE TABLE TAG
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME TEXT
);

CREATE TABLE ERROR_COMMENT_TAG
(
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    ERROR_COMMENT_ID BIGINT,
    TAG              BIGINT
)
